### ISSUE TITLE
spockito.Unroll does not adhere to the Gradle "--tests <pattern>" argument

### ISSUE THREAD

**Issue by roded** [tools4j/spockito#10] opened 2022-04-07 06:41 UTC
Seems like when running a Gradle test task with explicit tests inclusion via the --tests argument, spockito runs the unrolled tests even if their names do not adhere to the inclusion argument.

I.e.,
`:my-project:test --tests "*NoSuchTest*"`
will run all unrolled spockito tests.

**Comment by terzerm** [comment] 2022-04-07 11:21
Hi -- thanks for reporting this.
Can you please provide some more information?  E.g. which version of spockito are you referring to, and what junit version?

I tried to reproduce the problem directly inside the spockito project itself:
```
./gradlew :spockito-junit4:test --tests *NoSuchTest*

> Configure project :
spockito version=2.1-SNAPSHOT release=false

> Task :spockito-junit4:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spockito-junit4:test'.
> No tests found for given includes: [*NoSuchTest*](--tests filter)
```

similar for the junit5 module or when using the whole project

**Comment by roded** [comment] 2022-04-07 11:41
Sure. I'm using the latest spockito with JUnit4. i.e., `spockito-junit4:2.0` and Gradle 7.4.2.
I can try to create a test project if required.
Thanks for looking into this.

**Comment by roded** [comment] 2022-04-11 05:10
@terzerm Hope this helps: https://github.com/roded/spockito-issue-10

**Comment by terzerm** [comment] 2022-05-05 11:33
Hi again,
Sorry for the late reply.
If I comment out the "getByName<Test>" task in your build.gradle file it works as expected for me.
If anything then this seems to be more gradle. than spockito related, hence closing the issue.
Hope this helps.

**Closed as completed** 2022-05-05 11:35 UTC
Labels: question

**Comment by roded** [comment] 2022-05-06 14:59
Interesting. Thanks for looking into it.
